language: c

os: linux

compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-9 -y
  - sudo apt-get install cmake-3.15 -y
  - sudo apt-get install cppcheck -y
  - sudo apt-get install python2.7 -y

script:
    - mkdir build
    - cd build
    - cmake ../
    - make