language: c

os: linux

compiler: gcc

before_install:
  - sudo apt-get update -q
  - sudo apt-get install cppcheck -y
  - sudo apt-get install python2.7 -y
  - sudo apt-get install valgrind -y
  - sudo apt-get install libgtest-dev -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-9 -y
  - gwhere gcc-9
  - sudo update-alternatives --install /usr/bin/gсс gсс gсс-9 90
  - sudo apt-get install g++-9 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  - CMAKE_VERSION=3.15.4
  - CMAKE_VERSION_DIR=v3.15
  - CMAKE_OS=Linux-x86_64
  - CMAKE_TAR=cmake-$CMAKE_VERSION-$CMAKE_OS.tar.gz
  - CMAKE_URL=http://www.cmake.org/files/$CMAKE_VERSION_DIR/$CMAKE_TAR
  - CMAKE_DIR=$(pwd)/cmake-$CMAKE_VERSION
  - wget --quiet $CMAKE_URL
  - mkdir -p $CMAKE_DIR
  - tar --strip-components=1 -xzf $CMAKE_TAR -C $CMAKE_DIR
  - export PATH=$CMAKE_DIR/bin:$PATH

script:
    - ./linters/run.sh --local
    - mkdir build
    - cd build
    - cmake ../
    - make
    - ./Test
    - valgrind --tool=memcheck --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./idz_1 -i "../a.txt"